projectsite/cardquest/models.py
from django.db import models

# Create your models here.
class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        abstract = True
    
    
class Trainer(BaseModel):
    name = models.CharField(max_length=100, null=True, blank=True)
    birthdate = models.DateField(null=True, blank=True)
    location = models.CharField(max_length=250, null=True, blank=True)
    email = models.EmailField(max_length=100, null=True, blank=True)
    
    def __str__(self):
        return self.name
    
class PokemonCard(BaseModel):
    RARITY_CHOICES = (('Common', 'Common'), ('Uncommon', 'Uncommon'),('Rare', 'Rare'))
    
    CARDTYPE_CHOICES = (
        ('Fire', 'Fire'),
        ('Water', 'Water'),
        ('Grass', 'Grass'),
        ('Electric', 'Electric'),
        ('Psychic', 'Psychic'),
        ('Ice', 'Ice'),
        ('Dragon', 'Dragon'),
        ('Dark', 'Dark'),
        ('Normal', 'Normal'),
        ('Fighting', 'Fighting'),
        ('Flying', 'Flying'),
        ('Poison', 'Poison'),
        ('Ground', 'Ground'),
        ('Rock', 'Rock'),
        ('Bug', 'Bug'),
        ('Ghost', 'Ghost'),
        ('Steel', 'Steel'),
        ('Fairy', 'Fairy'),
    )
    
    name = models.CharField(max_length=100, null=True, blank=True)
    rarity = models.CharField(max_length=100, null=True, blank=True, choices=RARITY_CHOICES)
    hp = models.IntegerField(null=True, blank=True)
    card_type = models.CharField(max_length=100, null=True, blank=True, choices=CARDTYPE_CHOICES)
    attack = models.CharField(max_length=100, null=True, blank=True)
    description = models.CharField(max_length=250, null=True, blank=True)
    weakness = models.CharField(max_length=250, null=True, blank=True)
    card_number = models.IntegerField(null=True, blank=True)
    release_date = models.DateField(null=True, blank=True)
    evolution_stage = models.CharField(max_length=250, null=True, blank=True)
    abilities = models.CharField(max_length=250, null=True, blank=True)
    
    def __str__(self):
        return self.name
class Collection(BaseModel):
    card = models.ForeignKey(PokemonCard, blank=True, null=True, on_delete=models.CASCADE)
    trainer = models.ForeignKey(Trainer, blank=True, null=True, on_delete=models.CASCADE, related_name='collection_trainer')
    collection_date = models.DateField()
    

projectsite/cardquest/forms.py
from django.forms import ModelForm
from django import forms
from .models import Trainer, Collection, PokemonCard
class TrainerForm(ModelForm):
    birthdate = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'})) 
    class Meta:
        model = Trainer
        fields = "__all__"
        
class PokemonCardForm(ModelForm):
    release_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    class Meta:
        model = PokemonCard
        fields = "__all__"
        
class CollectionForm(ModelForm):
    collection_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    class Meta:
        model = Collection
        fields = "__all__"

projectsite/cardquest/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from cardquest.models import PokemonCard, Trainer, Collection
from cardquest.forms import TrainerForm, PokemonCardForm, CollectionForm
from django.urls import reverse_lazy
import json


class HomePageView(ListView):
    model = PokemonCard
    context_object_name = 'home'
    template_name = "base.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class TrainerList(ListView):
    model = Trainer
    context_object_name = 'trainer'
    template_name = 'trainer.html'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_queryset(self, *args, **kwargs):
        qs = super(TrainerList, self).get_queryset(*args, **kwargs)
        return qs   
    
class TrainerCreateView(CreateView):
    model = Trainer
    form_class = TrainerForm
    template_name = 'add.html'
    success_url = reverse_lazy('trainer-list')
    
class TrainerUpdateView(UpdateView):
    model = Trainer
    form_class = TrainerForm
    template_name = 'edit.html'
    success_url = reverse_lazy('trainer-list')
    
class TrainerDeleteView(DeleteView):
    model = Trainer
    template_name = 'delete.html'
    success_url = reverse_lazy('trainer-list')
    
# #Uses html premade list not database
# class PokemonCard(ListView):
#     model = PokemonCard
#     context_object_name = 'pokemon card'
#     template_name = 'pokemon-card.html'
#     paginate_by = 5

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         return context

#     def get_queryset(self, *args, **kwargs):
#         qs = super(PokemonCard, self).get_queryset(*args, **kwargs)
#         return qs
    
class PokemonCardListView(ListView):
    model = PokemonCard
    context_object_name = 'pokemoncard'
    template_name = "pokemoncards.html"
    paginate_by = 5
    json_file_path = 'data/pokemon_data.json'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pokemon_data = self.get_pokemon_data()
        context['pokemon_data'] = pokemon_data
        return context
    def get_pokemon_data(self):
        with open(self.json_file_path, 'r') as file:
            data = json.load(file)
        return data.get('pokemons', [])
    
class PokemonCreateView(CreateView):
    model = PokemonCard
    form_class = PokemonCardForm
    template_name = 'add.html'
    success_url = reverse_lazy('pokemoncard-list')
    
class PokemonUpdateView(UpdateView):
    model = PokemonCard
    form_class = PokemonCardForm
    template_name = 'edit.html'
    success_url = reverse_lazy('pokemoncard-list')
    
class PokemonDeleteView(DeleteView):
    model = PokemonCard
    template_name = 'delete.html'
    success_url = reverse_lazy('pokemoncard-list')
    
class CollectionListView(ListView):
    model = Collection
    context_object_name = 'collection'
    template_name = 'collection.html'
    paginate_by = 5

class CollectionCreateView(CreateView):
    model = Collection
    form_class = CollectionForm
    template_name = 'add.html'
    success_url = reverse_lazy('collection-list')    
    
class CollectionUpdateView(UpdateView):
    model = Collection
    form_class = CollectionForm
    template_name = 'edit.html'
    success_url = reverse_lazy('collection-list')
    
class CollectionDeleteView(DeleteView):
    model = Collection
    template_name = 'delete.html'
    success_url = reverse_lazy('collection-list')

projectsite/cardquest/templates/add.html
{% extends 'base.html' %}
    {% load static %}
    {% block content %}
    <form role="form" class="" action="" method="post" novalidate> 
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <br />
        <div class="form-group">
            <div class="col-md-12 col-sm-3">
                <button type='submit' class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
    {% endblock %}

projectsite/cardquest/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link rel="stylesheet" href="{% static '../static/css/style.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href='https://fonts.googleapis.com/css?family=Roboto Slab' rel='stylesheet'>
    <title>{% block title %} CardQuest Master {% endblock %}</title>
  </head>
  <body>

    <!-- navbar -->
    <section class="navbar">
      <a href="{% url 'home' %}" class="btn" id="active"> Home </a>
      <a href="{% url 'trainer-list' %}" class="btn"> Trainer </a>
      <a href="{% url 'pokemoncard-list' %}" class="btn"> Pokemon Card </a>
      <a href="{% url 'collection-list' %}" class="btn"> Collection </a>
    </section>

    <!-- Main content of your webpage -->
    <main>
      {% block content %}

      {% endblock %}
    </main>

    {% include 'includes/footer.html' %}
    
  </body>
</html>

projectsite/cardquest/templates/collection.html
{% extends 'collectionnavbarbase.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link rel="stylesheet" href="css/style.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href='https://fonts.googleapis.com/css?family=Roboto Slab' rel='stylesheet'>
    <title>Pokemon | Collection</title>
  </head>
  <body>
    <!--NAVBAR-->
    {% comment %} <section class="navbar">
      <a href="{% url 'home' %}" class="btn"> Home </a>
      <a href="{% url 'trainer-list' %}" class="btn"> Trainer </a>
      <a href="{% url 'pokemoncard-list' %}" class="btn"> Pokemon Card </a>
      <a href="{% url 'collection-list'%}" class="btn" id="active"> Collection </a>
    </section> {% endcomment %}
    {% comment %} {% include 'includes/navigationBar.html' %} {% endcomment %}
    {% block content %}
    <!--TRAINERS-->
    <main>
    <a href="{% url 'collection-add' %}" class="btn btn-outline-primary">Add New Collection</a><br>
    <section class="collection-container">
      <table class="styled-table">
        <tbody>
          <tr>
            <th>Card</th>
            <th>Trainer</th>
            <th>Collection date</th>
            <th>Action</th>
          </tr>
          {% for object in object_list %}
            <td>{{ object.card }}</td>
            <td>{{ object.trainer }}</td>
            <td>{{ object.collection_date}} </td>
            <td>
              <a href="collection_list/{{ object.id }}" >Edit</a> |
              <a href="collection_list/{{ object.id }}/delete" >Delete</a>
            </td>
          </tr>
          {% empty %}
          <tr>
          {% endfor %}

        </div>
        </tbody>
      </table>
    </section>
  </main>
  {% endblock %}
  {% include 'includes/footer.html' %}
  </body>
</html>

projectsite/cardquest/templates/collectionnavbarbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link rel="stylesheet" href="{% static '../static/css/style.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href='https://fonts.googleapis.com/css?family=Roboto Slab' rel='stylesheet'>
    <title>{% block title %} CardQuest Master {% endblock %}</title>
  </head>
  <body>

    <!-- navbar -->
    <section class="navbar">
      <a href="{% url 'home' %}" class="btn"> Home </a>
      <a href="{% url 'trainer-list' %}" class="btn"> Trainer </a>
      <a href="{% url 'pokemoncard-list' %}" class="btn"> Pokemon Card </a>
      <a href="{% url 'collection-list' %}" class="btn" id="active"> Collection </a>
    </section>

    <!-- Main content of your webpage -->
    <main>
      {% block content %}

      {% endblock %}
    </main>

    {% include 'includes/footer.html' %}
    
  </body>
</html>

projectsite/cardquest/templates/delete.html
{% extends 'base.html' %}
    {% load static %}
    {% block content %}
    <div class="card-body ">
        <form method="post">
            {% csrf_token %}
            <div class="form-row ">
                <p>Are you sure you want to delete "{{ object }}"?</p>
                {% include 'includes/form.html' %}
            </div>
            <input class="col-md-4 btn btn-primary" type="submit" value="Confirm">
        </form>
    </div>
    {% endblock %}

projectsite/cardquest/templates/edit.html
{% extends 'base.html' %}
    {% load static %}

{% block content %}
<form role="form" class="" action="" method="post" novalidate>
    {% include 'includes/form.html' %}
    {% csrf_token %}

    <br />
    <div class="form-group">
        <div class="col-md-12 col-sm-3">
            <button type='submit' class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
{% endblock %}

projectsite/cardquest/templates/includes/footer.html
<footer>
    <br />
    <br />
    <div>{% include 'includes/pagination.html' %}</div>
    <p>
      POKEMON<br />
      Gotta Catch 'Em All
    </p>
    <br>
    <div class="social-icons">
      <a href="https://github.com/developer" target="_blank" class="icon-link">
        <i class="fab fa-github"></i>
      </a>
      <a href="https://facebook.com/yourpage" target="_blank" class="icon-link">
        <i class="fab fa-facebook"></i>
      </a>
      <a href="https://instagram.com/youraccount" target="_blank" class="icon-link">
        <i class="fab fa-instagram"></i>
      </a>
      <!-- Add other social media icons similarly -->
    </div>
    <p>
      &copy; 2023 YourWebsiteName. All Rights Reserved.
    </p>
</footer>

projectsite/cardquest/templates/includes/form.html
{% load widget_tweaks %}
    {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">

            {% for error in form.non_field_errors %}
            <p{% if forloop.last %} class="mb-0" {% endif %}>{{ error }}</p>
            {% endfor %}
        </div>
    {% endif %}
    {% for field in form %}
        <div class="col-md-6">
            <div class="form-group">
            {% if field.field.widget.input_type == 'checkbox' %}
                <div class="form-check form-switch">
                    {% render_field field class="form-check-input ms-auto" %}
                    <label class="form-check-label text-body ms-3 text-truncate w-250 mb-0"
                    for="flexSwitchCheckDefault5">{{ field.label_tag }}</label>
                </div>
            {% else %}
                <label for="example-text-input" class="form-control-label">{{ field.label_tag}}</label>
                {% render_field field class="form-control" %}
            {% endif %}
            </div>
        </div>
        {% for error in field.errors %}
            <div class="invalid-feedback">
            {{ error }}
            </div>
        {% endfor %}
    {% endfor %}

projectsite/cardquest/templates/includes/navigationBar.html
<section class="navbar">
    <a href="{% url 'home' %}" class="btn"> Home </a>
    <a href="{% url 'trainer-list' %}" class="btn"> Trainer </a>
    <a href="{% url 'pokemoncard-list' %}" class="btn"> Pokemon Card </a>
    <a href="{% url 'collection-list'%}" class="btn"> Collection </a>
  </section>

projectsite/cardquest/templates/includes/pagination.html
{% if is_paginated %}
  <nav aria-label="Topics pagination" class="mb-4">
    <ul class="pagination">
      {% if page_obj.number > 1 %}
        <li class="page-item">
          <a class="page-link" href="?page=1">First</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">First</span>
        </li>
      {% endif %}

      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Previous</span>
        </li>
      {% endif %}

      {% for page_num in paginator.page_range %}
        {% if page_obj.number == page_num %}
          <li class="page-item active">
            <span class="page-link">
              {{ page_num }}
              <span class="sr-only">(current)</span>
            </span>
          </li>
        {% elif page_num > page_obj.number|add:'-3' and page_num < page_obj.number|add:'3' %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Next</span>
        </li>
      {% endif %}

      {% if page_obj.number != paginator.num_pages %}
        <li class="page-item">
          <a class="page-link" href="?page={{ paginator.num_pages }}">Last</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Last</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

projectsite/cardquest/templates/pokemoncards.html
{% extends 'pokemonnavbarbase.html' %}
{% load static %}
{% block content %}

  <section class="cards-container">
    <a href="{% url 'pokemoncard-add' %}" class="btn btn-outline-primary">Add New Card</a><br>
    <!-- Display Pokemon Cards -->
    {% for card in pokemoncard %}
      <div class="card-box">
        <div class="card">
          <div class="card-type" id="{{ card.card_type|lower }}">
          <div class="card-image" id="{{ card.card_type|lower }}-img">
          {% for pokemon in pokemon_data %}
            {% if pokemon.name == card.name %}
              <img src="{{ pokemon.image_url }}" alt="{{ pokemon.name }} Image">
            {% endif %}
          {% endfor %}
        </div>
        <div class="card-name">
          <h2 class="sbs">{{ card.name}}</h2>
          <h2 class="sbs" id="card-number">#00{{ card.card_number }}</h2>
          <hr />
        </div>
        <div class="card-rarity">
          <h3 class="rarity">Rarity:</h3>
          <h3 class="rarity" id="rare-text">{{ card.rarity }}</h3>
        </div>
        <table class="card-stats">
          <tbody>
            <tr>
              <th>HP:</th>
              <td>{{ card.hp }}</td>
            </tr>
            <tr>
              <th>Card Type:</th>
              <td>{{ card.card_type }}</td>
            </tr>
            <tr>
              <th>Attack:</th>
              <td>{{ card.attack }}</td>
            </tr>
            <tr>
              <th>Description:</th>
              <td>{{ card.description }}</td>
            </tr>
            <tr>
              <th>Weakness:</th>
              <td>{{ card.weakness }}</td>
            </tr>
            <tr>
              <th>Abilities:</th>
              <td>{{ card.abilities }}</td>
            </tr>
            <tr>
              <th>Action:</th> 
              <td>
                <a href="pokemoncard_list/{{ card.id }}" >Edit</a> |
                <a href="pokemoncard_list/{{ card.id }}/delete" >Delete</a>
              </td>
            </tr>
          </tbody>
        </table>
        <hr / >
        </div>
        </div>
      </div>
    {% endfor %}
    <dv><br><br><br></dv>
  </section>
{% endblock %}

projectsite/cardquest/templates/pokemonnavbarbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link rel="stylesheet" href="{% static '../static/css/style.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href='https://fonts.googleapis.com/css?family=Roboto Slab' rel='stylesheet'>
    <title>{% block title %} CardQuest Master {% endblock %}</title>
  </head>
  <body>

    <!-- navbar -->
    <section class="navbar">
      <a href="{% url 'home' %}" class="btn"> Home </a>
      <a href="{% url 'trainer-list' %}" class="btn"> Trainer </a>
      <a href="{% url 'pokemoncard-list' %}" class="btn" id="active"> Pokemon Card </a>
      <a href="{% url 'collection-list' %}" class="btn"> Collection </a>
    </section>

    <!-- Main content of your webpage -->
    <main>
      {% block content %}

      {% endblock %}
    </main>

    {% include 'includes/footer.html' %}
    
  </body>
</html>

projectsite/cardquest/templates/trainer.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link rel="stylesheet" href="{% static '../static/css/style.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href='https://fonts.googleapis.com/css?family=Roboto Slab' rel='stylesheet'>
    <title>Pokemon | Trainers</title>
  </head>
  <body>

    <!--NAVBAR-->
    <section class="navbar">
      <a href="{% url 'home' %}" class="btn"> Home </a>
      <a href="{% url 'trainer-list' %}" class="btn" id="active"> Trainer </a>
      <a href="{% url 'pokemoncard-list' %}" class="btn"> Pokemon Card </a>
      <a href="{% url 'collection-list' %}" class="btn"> Collection </a>
    </section>
    {% block content %}
    <!--TRAINERS-->
    <main>
    <a href="{% url 'trainer-add' %}" class="btn btn-outline-primary">Add New Trainer</a><br>
    <section class="trainers-container">
      <table class="styled-table">
        <tbody>
          <tr>
            <th>Trainer Name</th>
            <th>Birthdate</th>
            <th>Location</th>
            <th>Email</th>
            <th>Action</th>
          </tr>

          {% for object in object_list %}

          <!--ASH-->
            <td>{{ object.name }}</td>
            <td>{{ object.birthdate }}</td>
            <td>{{ object.location }}</td>
            <td>{{ object.email}} </td>
            <td>
            <a href="trainer_list/{{ object.id }}" >Edit</a> |
            <a href="trainer_list/{{ object.id }}/delete" >Delete</a>
            </td>
          </tr>
          {% empty %}
          <tr>
          {% endfor %}
        </tbody>
      </table>
    </section>
  </main>
  {% endblock %}
  {% include 'includes/footer.html' %}
  </body>
</html>

projectsite/cardquest/templates/trainer_add.html
{% extends 'base.html' %}
    {% load static %}
    {% block content %}
    <form role="form" class="" action="" method="post" novalidate> 
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <br />
        <div class="form-group">
            <div class="col-md-12 col-sm-3">
                <button type='submit' class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>
    {% endblock %}